apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: rag-jul26-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  rag-jul26-2
    app.kubernetes.io/part-of: rag-jul26-2  
  name: rag-jul26-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  rag-jul26-2 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  rag-jul26-2
    spec:
      containers:
      - env:
        - name: MODEL_ENDPOINT
          value: http://rag-jul26-2-model-server:8001
        - name: MODEL_NAME
          value: "instructlab/granite-7b-lab"
        image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
      - image: quay.io/maysunfaisal/chroma-uid:latest
        name: vectordb
        ports:
        - containerPort: 8000
        securityContext:
          runAsNonRoot: true